### ISSUE TITLE
Test Error with Robot trajectories overlay

### ISSUE THREAD

**Issue by vallq** [open-rmf/rmf-web#237]
Current Test with Assertion causes an error
`robot-trajectories-overlay.test.tsx`
```
it('smoke test', async () => {
    const settings = defaultSettings();
    let root: RenderResult;
    await waitFor(async () => {
      root = render(
        <LMap>
          <SettingsContext.Provider value={settings}>
            <RobotTrajectoriesOverlay
              bounds={mapBound}
              robots={robots}
              trajectories={[trajectoryValue]}
              conflicts={trajectoryConflict}
            />
          </SettingsContext.Provider>
        </LMap>,
      );
      screen.debug();
      expect(root.findAllByTestId('trajMarker')).toBeInTheDocument();
      root.unmount();
    });
  });
```
Start of Error Message
```
console.error
    Error: Uncaught [TypeError: pathAnim.getTotalLength is not a function]
        at reportException (/home/val/dev/rmf_web/src/rmf-web/packages/dashboard/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
```

The test will continue to run without stopping (time taken keeps increasing)

screen.debug
```
console.log
    <body>
      <div>
        <div
          class="leaflet-container leaflet-grab leaflet-touch-drag"
          style="position: relative;"
          tabindex="0"
        >
          <div
            class="leaflet-pane leaflet-map-pane"
            style="left: 0px; top: 0px;"
          >
            <div
              class="leaflet-pane leaflet-tile-pane"
            />
            <div
              class="leaflet-pane leaflet-shadow-pane"
            />
            <div
              class="leaflet-pane leaflet-overlay-pane"
            />
            <div
              class="leaflet-pane leaflet-marker-pane"
            />
            <div
              class="leaflet-pane leaflet-tooltip-pane"
            />
            <div
              class="leaflet-pane leaflet-popup-pane"
            />
          </div>
          <div
            class="leaflet-control-container"
          >
            <div
              class="leaflet-top leaflet-left"
            >
              <div
                class="leaflet-control-zoom leaflet-bar leaflet-control"
              >
                <a
                  aria-label="Zoom in"
                  class="leaflet-control-zoom-in"
                  href="#"
                  role="button"
                  title="Zoom in"
                >
                  +
                </a>
                <a
                  aria-label="Zoom out"
                  class="leaflet-control-zoom-out"
                  href="#"
                  role="button"
                  title="Zoom out"
                >
                  −
                </a>
              </div>
            </div>
            <div
              class="leaflet-top leaflet-right"
            />
            <div
              class="leaflet-bottom leaflet-left"
            />
            <div
              class="leaflet-bottom leaflet-right"
            >
              <div
                class="leaflet-control-attribution leaflet-control"
              >
                <a
                  href="https://leafletjs.com"
                  title="A JS library for interactive maps"
                >
                  Leaflet
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </body>

      at logDOM (node_modules/@testing-library/dom/dist/pretty-dom.js:82:13)
```

I've tried using `getAllBy` and `queryAllBy`, none of which produce the desired results. It seems that the elements are not yet rendered even though they have been wrapped in `act` with `await waitFor`

**Comment by koonpeng** [comment]
`pathAnim.getTotalLength is not a function`

was this with jsdom? If so you may need to mock that function. Not sure why it would suddenly fail now though.

**Comment by vallq** [comment]
The original test didn't have jsdom iirc! So there was no mock function, but if that's a possibility then I will take a look at it

**Comment by mxgrey** [comment]
Is this still an issue, or did the PRs fix it?

**Comment by koonpeng** [comment]
There was a PR that fixed a similar problem, @vallq can you update or close this if that PR also fixes this?

**Comment by vallq** [comment]
hello, yes it does fix the test. thanks @koonpeng, will close this now.
