### ISSUE TITLE
npm run bootstrap failed

### ISSUE THREAD

**Issue by desstiony** [open-rmf/rmf-web#292]
npm run bootstrap failed
```
> api-client@0.0.0 prepare /home/gh/rmf-web/packages/api-client
> node generate-models.js && npm run build

generate schemas:
Traceback (most recent call last):
  File "/home/gh/rmf-web/packages/api-client/generate-schemas.py", line 6, in <module>
    from api_server import models
  File "/home/gh/rmf-web/packages/api-server/api_server/models/__init__.py", line 16, in <module>
    from .task_summary import TaskSummary
  File "/home/gh/rmf-web/packages/api-server/api_server/models/task_summary.py", line 8, in <module>
    class TaskSummary(json_model(RmfTaskSummary, lambda x: x.task_id)):
  File "/home/gh/rmf-web/packages/api-server/api_server/models/task_summary.py", line 13, in TaskSummary
    RmfTaskSummary.STATE_PENDING,
AttributeError: type object 'TaskSummary' has no attribute 'STATE_PENDING'
child_process.js:674
    throw err;
    ^

Error: Command failed: python3 -m pipenv run python /home/gh/rmf-web/packages/api-client/generate-schemas.py
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at Object.<anonymous> (/home/gh/rmf-web/packages/api-client/generate-models.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 80160,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-client@0.0.0 prepare: `node generate-models.js && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api-client@0.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gh/.npm/_logs/2021-03-29T02_01_52_976Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@ bootstrap: `node scripts/bootstrap.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the root@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gh/.npm/_logs/2021-03-29T02_01_52_995Z-debug.log```

**Comment by koonpeng** [comment]
Make sure that you have the latest version of rmf, check that your message have this https://github.com/open-rmf/rmf_internal_msgs/blob/b6a583250948dcf6fd32fe32a1d8ba6a3d7a3787/rmf_task_msgs/msg/TaskSummary.msg#L17

**Comment by aaronchongth** [comment]
I assume this has been fixed, closing this ticket.
