### ISSUE TITLE
Pipeline failed: ros-translator failing after pydantic version upgrade

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#346]
ros-translator package is failing after Pydantic version upgrade

build(deps): bump pydantic from 1.8.1 to 1.8.2 https://github.com/open-rmf/rmf-web/pull/333

```
Summary: 1 package finished [16.1s]
/__w/rmf-web/rmf-web/packages/ros-translator
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/__w/rmf-web/rmf-web/packages/ros-translator/ros_translator/__main__.py", line 36, in <module>
    main()
  File "/__w/rmf-web/rmf-web/packages/ros-translator/ros_translator/__main__.py", line 29, in main
    target = importlib.import_module(f"ros_translator.{args.target}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/__w/rmf-web/rmf-web/packages/ros-translator/ros_translator/typescript/__init__.py", line 9, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

**Comment by koonpeng** [comment]
Should be fixed by #345
