### ISSUE TITLE
"Your Chrome version is null" error when lerna bootstrap rmf-dashboard-e2e

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf-web#431]
hello :wave:  i think there is a restriction of chromedriver in package-lock.json in rmf-web to version 85.0.1 that breaks lerna bootstrap --scope=rmf-dashboard-e2e when using Chrome versions > 85. 

```
ubuntu@ip-192-168-29-87:~/rmf-web$ lerna bootstrap --scope=rmf-dashboard-e2e
info cli using local version of lerna
lerna notice cli v4.0.0
lerna notice filter including "rmf-dashboard-e2e"
lerna notice filter including dependencies
lerna info filter [ 'rmf-dashboard-e2e' ]
lerna WARN bootstrap Installing local packages that do not match filters from registry
lerna info Bootstrapping 8 packages
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! npm install --no-save exited 1 in 'root'
lerna ERR! npm install --no-save stdout:

> fibers@4.0.3 install /home/ubuntu/rmf-web/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/home/ubuntu/rmf-web/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory '/home/ubuntu/rmf-web/node_modules/fibers/build'
Installed in `/home/ubuntu/rmf-web/node_modules/fibers/bin/linux-x64-83-glibc/fibers.node`

> chromedriver@85.0.1 install /home/ubuntu/rmf-web/node_modules/chromedriver
> node install.js

Your Chrome version is null
lerna ERR! npm install --no-save stderr:
../src/fibers.cc: In function ‘void uni::SetAccessor(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&))’:
../src/fibers.cc:355:87: warning: cast between incompatible function types from ‘uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)’} to ‘v8::AccessorNameGetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’} [-Wcast-function-type]
  355 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                                                       ^~~~~~
../src/fibers.cc:355:123: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} to ‘v8::AccessorNameSetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} [-Wcast-function-type]
  355 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                                                                                           ^~~~~~
In file included from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
../src/fibers.cc: At global scope:
/home/ubuntu/.cache/node-gyp/14.17.3/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/ubuntu/.cache/node-gyp/14.17.3/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/fibers.cc:930:1: note: in expansion of macro ‘NODE_MODULE’
  930 | NODE_MODULE(fibers, init)
      | ^~~~~~~~~~~
ChromeDriver installation failed TypeError: Cannot read property '1' of null
    at install (/home/ubuntu/rmf-web/node_modules/chromedriver/install.js:42:75)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm WARN karma-webpack@5.0.0 requires a peer of webpack@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@85.0.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@85.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-07-12T07_58_30_852Z-debug.log

```

**Comment by koonpeng** [comment]
The chromedriver is supposed to detect the installed chrome version, are you able to reproduce it?

**Comment by cnboonhan** [comment]
I did encounter this error when attempting to do a build on a freshly minted cloud machine. My steps were following the readme on https://github.com/open-rmf/rmf-web, but using rmf built from source, and targeting dashboard-e2e.

I installed chromium from Ubuntu snap in my last attempt, but I believe I did try installing chrome using dkpg as well.

**Comment by cnboonhan** [comment]
I believe that I wrongly assumed Chromium would work. After installing Chrome 91 using dpkg, the build was successful. This is even when chromium snap is also installed.
