### ISSUE TITLE
Missing attribute to_pydantic when restarting rmf-server

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf-web#478]
Using kubernetes on latest main. This error seems to appear when restarting the rmf-server image without restarting rmf-server-db. This might break deployments if only the rmf-server crashes / needs to be restarted.
```
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 540, in lifespan
    async for item in self.lifespan_context(app):
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 481, in default_lifespan
    await self.startup()
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 516, in startup
    await handler()
  File "/usr/local/lib/python3.8/dist-packages/api_server/app.py", line 164, in on_startup
    await self._load_states()
  File "/usr/local/lib/python3.8/dist-packages/api_server/app.py", line 202, in _load_states
    door_health = [x.to_pydantic() for x in await ttm.DoorHealth.all()]
  File "/usr/local/lib/python3.8/dist-packages/api_server/app.py", line 202, in <listcomp>
    door_health = [x.to_pydantic() for x in await ttm.DoorHealth.all()]
AttributeError: 'DoorHealth' object has no attribute 'to_pydantic'
```

**Comment by cnboonhan** [comment]
i believe the function call here https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/api_server/app.py#L202 
used to be defined here  https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/api_server/app.py#L202
but no longer exists in main.

In the specific scenario when there are DoorHealth entries during rmf-server startup ( for example in the case of persistent database ) rmf-server will fail to continue execution.

Was `to_pydantic` refactored to another function?
