### ISSUE TITLE
[Other issue]: ModuleNotFoundError: No module named 'rmf_building_map_msgs'

### ISSUE THREAD

**Issue by rmj1405** [open-rmf/rmf-web#875]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I was able to run the api-server and rmf-dashboard just fine using `packages/dashboard` and `packages/api-server` until this error popped up out of nowhere. I am not sure how and where to be installing the missing module. I even tried on a new fresh installation of rmf and rmf web and the same error popped up.

My system:
Ubuntu 22.04
ROS2 Humble
Open-RMF latest version

```
rmj@RMF-Ubuntu-22:~/rmf-web/rmf-web/packages/api-server$ pnpm start
> api-server@0.0.0 start /home/rmj/rmf-web/rmf-web/packages/api-server
> rm -rf run && mkdir -p run/cache && RMF_API_SERVER_CONFIG=sqlite_local_config.py ../../scripts/pipenv run python -m api_server

Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/rmj/rmf-web/rmf-web/packages/api-server/api_server/__main__.py", line 5, in <module>
    from .app import app
  File "/home/rmj/rmf-web/rmf-web/packages/api-server/api_server/app.py", line 18, in <module>
    from . import gateway, ros, routes
  File "/home/rmj/rmf-web/rmf-web/packages/api-server/api_server/gateway.py", line 15, in <module>
    from rmf_building_map_msgs.msg import AffineImage as RmfAffineImage
ModuleNotFoundError: No module named 'rmf_building_map_msgs'
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by aaronchongth** [comment]
Make sure you source your RMF colcon workspace before running `pnpm start` for the `api-server`. This is because the `api-server` uses `rclpy` and some of the internal ROS 2 messages.

If you followed the instructions to build the workspace from `github.com/open-rmf/rmf`, the path would be

```
source ~/rmf_ws/install/setup.bash
cd ~/rmf-web/rmf-web/packages/api-server
pnpm start
```
